import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import "@/styles/theme.css";

export const metadata: Metadata = {
  title: "Novi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
